#**Archisha Sinha**
##Course: Deep Learning
##Title: ANN Feedforwarding without Tensorflow on Iris Dataset


In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Reading the Iris dataset from a CSV file
df = pd.read_csv("/content/Iris (1).csv")

In [3]:
# Displaying the first 7 rows of the dataset
df.head(7)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa

In [4]:
# One-hot encoding the 'Species' column
species = pd.get_dummies(df["Species"])

In [5]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
species.head(5)

Iris-setosa  Iris-versicolor  Iris-virginica
0            1                0               0
1            1                0               0
2            1                0               0
3            1                0               0
4            1                0               0

In [7]:
# Dropping the 'Species' column from the original dataset
df.drop('Species', axis=1, inplace=True)

In [8]:
# Standardizing the feature values using StandardScaler
from sklearn.preprocessing import StandardScaler

In [9]:
std_scaler= StandardScaler()  #So that all the features come down to same scale

In [10]:
df_scaled= std_scaler.fit_transform(df)

In [11]:
df_scaled

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [12]:
# Creating a new DataFrame with standardized features
df_transformed= pd.DataFrame(df_scaled, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])

In [13]:
# Displaying the transformed dataset
df_transformed.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.900681      1.032057      -1.341272     -1.312977
1      -1.143017     -0.124958      -1.341272     -1.312977
2      -1.385353      0.337848      -1.398138     -1.312977
3      -1.506521      0.106445      -1.284407     -1.312977
4      -1.021849      1.263460      -1.341272     -1.312977

In [14]:
df_transformed

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.900681      1.032057      -1.341272     -1.312977
1        -1.143017     -0.124958      -1.341272     -1.312977
2        -1.385353      0.337848      -1.398138     -1.312977
3        -1.506521      0.106445      -1.284407     -1.312977
4        -1.021849      1.263460      -1.341272     -1.312977
..             ...           ...            ...           ...
145       1.038005     -0.124958       0.819624      1.447956
146       0.553333     -1.281972       0.705893      0.922064
147       0.795669     -0.124958       0.819624      1.053537
148       0.432165      0.800654       0.933356      1.447956
149       0.068662     -0.124958       0.762759      0.790591

[150 rows x 4 columns]

In [15]:
# Concatenating the standardized features with the one-hot encoded species
Iris_df = pd.concat([df_transformed, species], axis=1)


In [16]:
# Displaying the first few rows of the concatenated DataFrame
Iris_df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
0      -0.900681      1.032057      -1.341272     -1.312977            1   
1      -1.143017     -0.124958      -1.341272     -1.312977            1   
2      -1.385353      0.337848      -1.398138     -1.312977            1   
3      -1.506521      0.106445      -1.284407     -1.312977            1   
4      -1.021849      1.263460      -1.341272     -1.312977            1   

   Iris-versicolor  Iris-virginica  
0                0               0  
1                0               0  
2                0               0  
3                0               0  
4                0               0

In [17]:
# Extracting the input features
input = Iris_df.iloc[:, 0:4]

In [18]:
# Displaying the shape of the input features
input.shape

(150, 4)

In [19]:
# Printing the input features
print(input)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.900681      1.032057      -1.341272     -1.312977
1        -1.143017     -0.124958      -1.341272     -1.312977
2        -1.385353      0.337848      -1.398138     -1.312977
3        -1.506521      0.106445      -1.284407     -1.312977
4        -1.021849      1.263460      -1.341272     -1.312977
..             ...           ...            ...           ...
145       1.038005     -0.124958       0.819624      1.447956
146       0.553333     -1.281972       0.705893      0.922064
147       0.795669     -0.124958       0.819624      1.053537
148       0.432165      0.800654       0.933356      1.447956
149       0.068662     -0.124958       0.762759      0.790591

[150 rows x 4 columns]


In [20]:
# Initializing weights and biases for the neural network
np.random.seed(42)
w_i_h1 = np.random.rand(4, 1)
w_i_h2 = np.random.rand(4, 1)
w_h_o1 = np.random.rand(2, 1)
w_h_o2 = np.random.rand(2, 1)
w_h_o3 = np.random.rand(2, 1)
bias1 = np.random.rand(1)
bias2 = np.random.rand(1)

In [21]:
# Displaying the initialized weights and biases
print(w_i_h1)
print('\n')
print(w_i_h2)
print('\n')
print(w_h_o1)
print('\n')
print(w_h_o2)
print('\n')
print(w_h_o3)
print('\n')
print(bias1)
print('\n')
print(bias2)
print('\n')

[[0.37454012]
 [0.95071431]
 [0.73199394]
 [0.59865848]]


[[0.15601864]
 [0.15599452]
 [0.05808361]
 [0.86617615]]


[[0.60111501]
 [0.70807258]]


[[0.02058449]
 [0.96990985]]


[[0.83244264]
 [0.21233911]]


[0.18182497]


[0.18340451]




In [22]:
# Defining the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [23]:
# Testing the sigmoid function with 0
sigmoid(0)

0.5

In [24]:
# Calculating the weighted sum and activation for hidden layer neurons
z2_1 = np.dot(input, w_i_h1) + bias1
z2_2 = np.dot(input, w_i_h2) + bias2
h2_1 = sigmoid(z2_1)
h2_2 = sigmoid(z2_2)

In [25]:
# Displaying the shapes of intermediate variables
z2_1.shape
z2_2.shape
h2_1.shape
h2_2.shape

(150, 1)

In [26]:
# Combining the hidden layer neurons
h2 = np.append(h2_1, h2_1, axis=1)
h2.shape
print(h2)

[[0.28046573 0.28046573]
 [0.10593928 0.10593928]
 [0.13879898 0.13879898]
 [0.11842493 0.11842493]
 [0.3170122  0.3170122 ]
 [0.58813899 0.58813899]
 [0.21242753 0.21242753]
 [0.2375955  0.2375955 ]
 [0.07044872 0.07044872]
 [0.12455428 0.12455428]
 [0.41960762 0.41960762]
 [0.22880931 0.22880931]
 [0.0947476  0.0947476 ]
 [0.0685752  0.0685752 ]
 [0.59682731 0.59682731]
 [0.81893726 0.81893726]
 [0.54730211 0.54730211]
 [0.29662004 0.29662004]
 [0.54827875 0.54827875]
 [0.45963167 0.45963167]
 [0.28881875 0.28881875]
 [0.42479587 0.42479587]
 [0.24683447 0.24683447]
 [0.26480334 0.26480334]
 [0.25158614 0.25158614]
 [0.11875484 0.11875484]
 [0.27550533 0.27550533]
 [0.29835468 0.29835468]
 [0.24661118 0.24661118]
 [0.15440974 0.15440974]
 [0.13295951 0.13295951]
 [0.30428742 0.30428742]
 [0.59535222 0.59535222]
 [0.68554282 0.68554282]
 [0.12455428 0.12455428]
 [0.15048785 0.15048785]
 [0.30954463 0.30954463]
 [0.12455428 0.12455428]
 [0.08306264 0.08306264]
 [0.24591384 0.24591384]


In [27]:
# Calculating the weighted sum and activation for output layer neurons
z3_1= np.dot(h2, w_h_o1)
z3_2= np.dot(h2, w_h_o2)
z3_3= np.dot(h2, w_h_o3)

In [28]:
o1= sigmoid(z3_1)
o2= sigmoid(z3_2)
o3= sigmoid(z3_3)

In [29]:
# Displaying the shapes of intermediate variables
z3_1.shape
z3_2.shape
z3_3.shape
o1.shape
o2.shape
o3.shape

(150, 1)

In [30]:
# Extracting target values and calculating errors
t1 = np.array(Iris_df.iloc[:, 4])
t1 = t1.reshape((-1, 1))
t2 = np.array(Iris_df.iloc[:, 5])
t2 = t2.reshape((-1, 1))
t3 = np.array(Iris_df.iloc[:, 6])
t3 = t3.reshape((-1, 1))
e1 = t1 - o1
e2 = t2 - o2
e3 = t3 - o3

In [31]:
# Displaying the shapes of error variables
print(e1.shape)
print(e2.shape)
print(e3.shape)

(150, 1)
(150, 1)
(150, 1)


In [32]:
# Calculating total error
total_error = np.multiply(e1, e1) + np.multiply(e2, e2) + np.multiply(e3, e3)
print(np.sum(total_error))

145.59010322084401
